### ISSUE TITLE
Events : alignement colonnes

### ISSUE THREAD

**Issue by nerik** [jblanche/lab212-Tracker#21]
Aligner colonnes entre différents tableaux (soon, past différentes années)
Élargir colonne ville, ça fait chelou par exeple avec Enghien les bains

**Comment by jblanche** [comment]
Pour le coup j'ai viré le pays, trop compliqué à gérer à l'affichage sinon, est-ce problématique ? 
Peut être qu'on peut le concatener à la ville quand ce n'est pas france ?
