### ISSUE TITLE
About : Mettre à jour le texte de présentation + bios de chaque membre. Possible de rendre ça éditable dans l'admin ?

### ISSUE THREAD

**Issue by pierrethr** [jblanche/lab212-Tracker#39]
Texte de présentation en anglais :

Lab212 is a multimedia collective, founded in 2008 by some friends.
The collective is now made of 10 members whom skills in different fields allow them to deal with artistic, pedagogic or even commercial projects.

From UX design to graphic design, programming, electronics and technical design, Lab212 is able to take care of most of the aspects required by innovative interactive projects.
By its sensible, poetic and tangible approach of interactive design, Lab212’s projects try to empower users and cast a different light on the technology surrounding our daily life.
Through its creations, Lab212 invite people to think about our relation with the world we live in and the people we live with.

By following a user-centered approach, the collective creates strongs, playful and inspiring interactive experiences which transform technology into something more.
Since its creation, Lab212 has many opportunities to exhibit its works both in french and international events including:  Fête de la Science (France), Festival International de l'Affiche et du Graphisme de Chaumont (France), Cube Festival (France), FICAM festival (Morocco),
OneDotZero (China, Russia, UK), Digital Content Expo (Japan), Campus Party (Spain, Colombia, Mexico), and more.

**Comment by jblanche** [comment]
J'ai du réduire un poil deux bios (Pedro et Erik) pour que ça tienne dans des cases de même taille pour le monde. J'espère que ça le fait.
